apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-httpd
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: httpd-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: httpd-server
          image: httpd
          ports:
            - containerPort: 80

