apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-nginx
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-server
          image: nginx
          ports:
            - containerPort: 80
