apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: myhttpd
    image: httpd
  - name: mybusybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
